services:
  # Backend Symfony
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      APP_ENV: dev
      APP_SECRET: your-secret-key-here
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/var/cache
      - /var/www/html/var/log
    ports:
      - "8000:8000"
    networks:
      - cardgame_network

  # Frontend Vue.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - cardgame_network
    command: npm run dev

  # Nginx pour servir l'application en production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - cardgame_network

networks:
  cardgame_network:
    driver: bridge 