framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    php_errors:
        log: true
    http_client:
        scoped_clients:
            # configure a scoped HTTP client for the API
            api_client:
                base_uri: 'https://api.github.com/'
                headers:
                    Accept: 'application/vnd.github.v3+json'
                extra:
                    curl:
                        CURLOPT_SSL_VERIFYPEER: false 